# vertex.yaml
server:
  port: 6380
  adress: "0.0.0.0"
  ssl: false

persistence:
  enabled: true
  snapshot_interval: 60
  append_only: false
  path: "/etc/vertex/data"

state:
  max_key_age: 7d
  max_size: 100MB
  max_allowed_entries: 100000

logging:
  level: info
  path: "/var/log/"
  max_size: 10MB
  max_backups: 3
  max_age: 7d
