name: Approve PR if Author is Owner

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

jobs:
  check-owner:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR author
      id: check
      uses: actions/github-script@v6
      with:
        script: |
          const repoOwner = context.repo.owner;
          const prAuthor = context.payload.pull_request.user.login;

          console.log(`Repository owner: ${repoOwner}`);
          console.log(`PR Author: ${prAuthor}`);

          if (prAuthor !== repoOwner) {
            core.setFailed("The PR author is not the repo owner. Approval not granted.");
          }

    - name: Approve PR
      if: success()
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.BOT_PAT }}

    - name: Notify if not approved
      if: failure()
      run: echo "The PR author is not the repo owner. Approval not granted."
